insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WTXAR001','Texas','Arlington');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WNWNW002','New York','New York');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WCALA003','Los Angeles','California');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WILCH004','Chicago','Illinois');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WTXHU005','Houston','Texas');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WARPH006','Phoenix','Arizona');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WPNPH007','Philadelphia','Pennsylvania');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WTXSA008','San Antonio','Texas');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WCASD009','San Diego','California');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WTXDA010','Dallas','Texas');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WCASJ011','San Jose','California');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WFLJV012','Jacksonville','Florida');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WOHCL013','Columbus','Ohio');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WNCCH014','Charlotte','North Carolina');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WCASF015','San Francisco','California');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WWASE016','Seattle','Washington');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WCODN017','Denver','Colorado');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WMABO018','Boston','Massachusetts');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WTENA019','Nashville','Tennessee');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('WNVLV020','Las Vegas','Nevada');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('STXAR001','Texas','Arlington');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('SNWNW002','New York','New York');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('SCALA003','Los Angeles','California');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('SILCH004','Chicago','Illinois');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('STXHU005','Houston','Texas');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('SARPH006','Phoenix','Arizona');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('SPNPH007','Philadelphia','Pennsylvania');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('STXSA008','San Antonio','Texas');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('SCASD009','San Diego','California');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('STXDA010','Dallas','Texas');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('SCASJ011','San Jose','California');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('SFLJV012','Jacksonville','Florida');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('SOHCL013','Columbus','Ohio');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('SNCCH014','Charlotte','North Carolina');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('SCASF015','San Francisco','California');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('SWASE016','Seattle','Washington');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('SCODN017','Denver','Colorado');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('SMABO018','Boston','Massachusetts');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('STENA019','Nashville','Tennessee');
insert into F21_S001_2_Outlet (Outlet_id,City,State) values ('SNVLV020','Las Vegas','Nevada');
